line-length = 100
exclude = ["versioneer.py", "rtctools_interface/_version.py"]

target-version = "py310"

[lint]

ignore = [
	"B904", # Fix someday: raising exceptions within except
]
select = [
	"B",  # flake8-bugbear
	"C4", # flake8-comprehensions
	"E",  # default / pycodestyle
	"F",  # default / pyflakes
	"I",  # isort
	"UP", # pyupgrade
	"W",  # pycodestyle
]
